### PR TITLE
Update bot.py

### PR DESCRIPTION
**Pull request by Selfie-bd**

### CODE REVIEW

**Comment by iAkashPattnaik** [comment]
Waah bsdk!

**Comment by IndrajeethY** [comment]
@Selfie-bd Pro

**Comment by xditya** [comment]
K, you done?
Closing now.

**Comment by IndrajeethY** [comment]
@xditya Lmao

**Comment by IndrajeethY** [comment]
@TAMILVIP007 Hurr

**Comment by IndrajeethY** [comment]
@TAMILVIP007 Stfu

**Comment by iAkashPattnaik** [comment]
> K, you done? Closing now.

\+

**Comment by xdity-is-gay** [comment]
@xditya Say With Me @Xditya Is Gay !!! 😏😏😏😏

**Comment by xdity-is-gay** [comment]
@xdity-is-gay

**Pull request closed without merging**
